---
- name: Install Apache again.
  hosts: all
  become: true

  vars:
    # Default to install apache on ubuntu. 
    apache_package: apache2
    apache_service: apache2

  handlers:
    - name: restart apache
      service: 
        name: "{{ apache_service }}"
        state: restarted

  pre_tasks:
    - name: Override Apache vars for Red Hat.
      set_fact:
        apache_backend: httpd
        apache_service: httpd
      when: ansible_os_family == 'RedHat'
  
  tasks:
    - name: Ensure apache is installed.
      package:
        name: "{{ apache_package }}"
        state: present

    - name: Copy a webpage.
      copy:
        content: |
          <html>
          <head>
            <title>Hello World!</title>
          </head>
          </html>
        dest: /var/www/html/index.html
      notify: restart_apache

    - name: Ensure the Apache server is running and starts at boot.
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: true
